name: Godot GUT Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            libfontconfig1 \
            libwebkit2gtk-4.1-0

      - name: Import project
        run: godot --headless --import --quit

      - name: Run GUT tests
        run: |
          godot --headless \
          --path "$PWD" \
          -s addons/gut/gut_cmdln.gd \
          -gdir=res://test/settings_menu_tests \
          -gexit
