name: Godot Shop Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci: 4.6.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run test_shop.gd
        run: godot --headless -s addons/gut/gut_cmdln.gd -gfile=res://test/test_shop.gd -gexit
